# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [6]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Original Array: ")
print(arr)
arr_2d = np.reshape(arr, (2, 5))
print("Converted Array: ")
print(arr_2d)

Original Array: 
[0 1 2 3 4 5 6 7 8 9]
Converted Array: 
[[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [25]:
a = np.array([[0,1, 2, 3,4],[5,6,7,8,9]])
b = np.array([[1,1,1,1,1],[1,1,1,1,1]])
print("Vertically stacked Arrays: ")
np.vstack((a,b))


Vertically stacked Arrays: 


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [8]:
x = np.array((0,1,2,3,4,1,1,1,1,1))
y = np.array((5,6,7,8,9,1,1,1,1,1))
print("Horizontally stacked Arrays: ")
np.hstack((x,y))


Horizontally stacked Arrays: 


array([0, 1, 2, 3, 4, 1, 1, 1, 1, 1, 5, 6, 7, 8, 9, 1, 1, 1, 1, 1])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [9]:
origarr = np.arange(15).reshape(1,3,5)
print("Original array: ")
print(origarr)
newarr = origarr.flatten()
print("Flat 1d array: ")
newarr


Original array: 
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]]
Flat 1d array: 


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [22]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
c = a.flatten()
c


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [11]:
arrdim = np.arange(15).reshape(-1,3)
arrdim


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [12]:
arrayin = np.arange(25).reshape(5,5)
print("Original Array: ")
print(arrayin)
print("Square of the array: ")
np.square(arrayin)

Original Array: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Square of the array: 


array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [13]:
np.random.seed(123)
arraynrr = np.random.randint(30, size = (5,6))
print("Original Array: ")
print(arraynrr)
print("Mean of the array: ")
arraynrr.mean()

Original Array: 
[[13  2 28  2  6 17]
 [19 10 27 25 22  1]
 [ 0 17 15  9  0 14]
 [ 0 15 25 19 14 29]
 [ 4  0 16  4 17 23]]
Mean of the array: 


13.1

## Question:9

### Find the standard deviation of the previous array in Q8?

In [14]:
np.std(arraynrr)

9.278469701410897

## Question:10

### Find the median of the previous array in Q8?

In [15]:
np.median(arraynrr)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [16]:
np.transpose(arraynrr)

array([[13, 19,  0,  0,  4],
       [ 2, 10, 17, 15,  0],
       [28, 27, 15, 25, 16],
       [ 2, 25,  9, 19,  4],
       [ 6, 22,  0, 14, 17],
       [17,  1, 14, 29, 23]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [17]:
arraynewi = np.arange(16).reshape(4,4)
print(arraynewi)
x = np.diagonal(arraynewi)
print("Sum of diagonal elements: ")
print(x.sum())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Sum of diagonal elements: 
30


## Question:13

### Find the determinant of the previous array in Q12?

In [18]:
np.linalg.det(arraynewi)

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [19]:
arrayque = np.arange(10)
print(arrayque)
print(np.percentile(arrayque,5))
print(np.percentile(arrayque,95))

[0 1 2 3 4 5 6 7 8 9]
0.45
8.549999999999999


## Question:15

### How to find if a given array has any null values?

In [20]:
arrayque = np.arange(10)
print(arrayque)
np.isnan(arrayque)

[0 1 2 3 4 5 6 7 8 9]


array([False, False, False, False, False, False, False, False, False,
       False])