# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [3]:
import numpy as np

2. Create a null vector of size 10 

In [4]:
nullvector=np.zeros(10)

3. Create a vector with values ranging from 10 to 49

In [5]:
import numpy as np
x= np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Find the shape of previous array in question 3

In [6]:
import numpy as np
x= np.arange(10,50)
x.shape

(40,)

5. Print the type of the previous array in question 3

In [7]:
import numpy as np
x= np.arange(10,50)
type(x)

numpy.ndarray

6. Print the numpy version and the configuration


In [8]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.19.3
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


7. Print the dimension of the array in question 3


In [9]:
import numpy as np
x= np.arange(10,50)
x.ndim

1

8. Create a boolean array with all the True values

In [10]:
import numpy as np
x= np.arange(10,50)
x>9

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

9. Create a two dimensional array




In [11]:
import numpy as np
y=np.random.randn(2,2)
y

array([[-0.44870416,  0.81020627],
       [ 1.16045866, -2.03339115]])

In [12]:
10. Create a three dimensional array



SyntaxError: invalid syntax (<ipython-input-12-26f528fba201>, line 1)

In [13]:
import numpy as np
z= np.random.randn(2,2,3)
z

array([[[-0.13628176, -0.15412111, -0.37714882],
        [-1.21949215,  0.92173106,  0.64768555]],

       [[ 0.61116768,  0.3972162 , -0.08271749],
        [ 0.01705375, -0.48439928,  0.37849783]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [14]:
import numpy as np
a=np.arange(1,12)
a=a[::-1]

12. Create a null vector of size 10 but the fifth value which is 1 

In [15]:
import numpy as np
b=np.zeros(10)
b[5-1]=1
b

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [16]:
import numpy as np
c=np.ones((3,3))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [17]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr=arr.astype('float64')
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [18]:
import numpy as np
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

17. Extract all odd numbers from arr with values(0-9)

In [19]:
import numpy as np
d=np.arange(1,10,2)
d


array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [20]:
import numpy as np
np.array([1,3,5,7,9])=[-1,-1,-1,-1]

SyntaxError: cannot assign to function call (<ipython-input-20-5f73cefb033a>, line 1)

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [21]:
import numpy as np
arr = np.arange(10)
arr[[5,6,7,8]]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [22]:
import numpy as np
e=np.zeros((4,4))
e[1:-1,1:-1]=1
e

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [23]:
import numpy as np
arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])
arr2d[1][1]=12
arr2d


array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [47]:
import numpy as np
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [72]:
import numpy as np
a2d=np.array([1,2,3,4,5,6,7,8,9])
np.reshape(a2d[(-1,5)])
a2d



IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [55]:
import numpy as np
b2d=np.array([[0,1,2],[3,4,5],[6,7,8]])
b2d[1][1]

4

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [58]:
import numpy as np
b3d=np.array([[0,1,2],[3,4,5],[6,7,8]])
b3d
b3d[(0,0),(1,1)]

array([1, 1])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [70]:
import numpy as np
x=np.random.randn(10,10)
minimum=np.min(x)
maximum=np.max(x)
print("maximunm=" ,maximum)
print("minimum=" ,minimum)


maximunm= 2.470416974564178
minimum= -2.655262180660449


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [75]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
y=np.intersect1d(a,b)
y

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [126]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [128]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])   
data = np.random.randn(7, 4)
print(names!='Will')
print(data[names!='Will'])

[ True  True False  True False  True  True]
[[-0.54166148 -0.17279851  0.13508521 -0.8195125 ]
 [ 0.63946208  2.08983051 -0.71159849  0.21418268]
 [-0.53063649 -0.68754379 -0.5789606  -0.1055939 ]
 [-0.56201966  0.54487148  0.58314511  2.53337649]
 [ 1.96851038  0.48936582  0.38370316 -0.17818968]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [127]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])   
data = np.random.randn(7, 4)
b=(names!='Will') & (names!='Joe')
print(b)
print(data[b])

[ True False False  True False False False]
[[-0.67412144 -0.93795036  0.46424123  0.98130648]
 [-1.5004006   2.3907174  -0.50527015 -1.53191466]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [89]:
import numpy as np
e2d=np.random.uniform(1,15, size=(5,3))
e2d
#array([[-1.18935238, -0.40600698, -0.80004128],
#       [ 0.77013007, -1.59360643,  0.90270635],
 #      [-0.37481199, -0.08652814,  1.32603341],
  #     [ 2.23347389,  0.11104144,  0.22391165]])

array([[12.08058863, 11.20739141,  3.1441647 ],
       [ 8.41075351, 11.25113413,  2.83909942],
       [ 6.36472338, 11.54008099,  4.25278411],
       [ 6.22417332,  6.67928694,  7.14723512],
       [ 1.20941125,  6.28266314,  9.96694678]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [91]:
import numpy as np
f3d= np.random.uniform(1,16, size=(2,2,4))
f3d

array([[[ 6.42766697,  7.7712956 , 15.8830369 ,  6.02618874],
        [10.19561157,  8.0321219 ,  4.78248694,  7.12759416]],

       [[ 5.86961938,  6.84140562,  8.41447765,  2.97707699],
        [ 8.17519639,  5.82243681,  6.29651305,  2.68483866]]])

33. Swap axes of the array you created in Question 32

In [93]:
import numpy as np
z=np.swapaxes(f3d,0,2)
z

array([[[ 6.42766697,  5.86961938],
        [10.19561157,  8.17519639]],

       [[ 7.7712956 ,  6.84140562],
        [ 8.0321219 ,  5.82243681]],

       [[15.8830369 ,  8.41447765],
        [ 4.78248694,  6.29651305]],

       [[ 6.02618874,  2.97707699],
        [ 7.12759416,  2.68483866]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [96]:
import numpy as np
aray=np.array([1,2,3,4,5,6,7,8,9,10])
square=np.square(aray)
square

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [110]:
import numpy as np
g= np.random.uniform(0,12,size=(1,12))
h=np.random.uniform(0,12,size=(1,12))
z=np.maximum(g,h)
z


array([[ 7.55930714,  0.99729507,  5.67888958,  6.33723353, 11.86508825,
        10.85183401,  7.28857345,  7.14277868,  8.14639233,  7.97110742,
         0.80590533,  9.04753238]])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [125]:
import numpy as np
array = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
ar=np.unique(array)
print("unique values :",ar)
b=np.sort(ar)
print(b)


array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
    b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [122]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
result= np.setdiff1d(a,b)
result

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [117]:
import numpy as np
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 

newColumn = np.array([[10,10,10]])

sampleArray[:,1] = newColumn[:,2]
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [118]:
import numpy as np
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
result= np.dot(x,y)
result

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [121]:
import numpy as np
last = np.random.randn(4,5)
cs= np.cumsum(last)
cs

array([-0.72006063, -0.40528965, -1.65251451, -0.9248486 , -1.23309435,
       -1.79105432, -0.50309557, -1.20748471, -2.12926111,  1.05999067,
       -0.58376004,  0.60747091,  0.62975087, -0.27604444, -1.32065381,
       -2.29090593, -1.12387094, -2.25694715, -2.33360211, -1.95436478])